[package]
name = "hdl"
version = "0.1.0"
edition = "2021"

[dependencies]
"hdllang" = {path = "hdllang"}
"miette" = {version = ">=5.5", features = ["fancy"]}
"thiserror" = "1.0"
"clap" = {version = "4.1.8", features=["cargo"]}
