[package]
name = "hdllang"
version = "0.1.0"
edition = "2021"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.9"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"miette" = ">=5.5"
"logos" = "0.12.1"
"thiserror" = "1.0"
"bimap" = "0.6.2"
lalrpop-util = {version = "0.19.7",  features = ["lexer"]}
"regex" = "1"