name: Main CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    name: Cargo build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "post-cargo-build"
    
  cargo-test:
    name: Cargo test
    runs-on: ubuntu-latest
    needs: [cargo-build]
    steps:
    - uses: Swatinem/rust-cache@v2
      with:
          shared-key: "post-cargo-build"
    - name: Tests
      run: cargo test -p hdl -p hdllang --verbose
    
# TODO add iverilog tests
# TODO add fuzzer tests
