name: Main CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  hdllang-build:
    name: Build hdllang
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build hdllang
      working-directory: ./hdlc
      run: cargo build --verbose
    
  hdllang-test:
    name: Test hdllang
    runs-on: ubuntu-latest
    needs: [hdllang-build]
    steps:
    - uses: actions/checkout@v3
    - name: Test hdllang
      working-directory: ./hdlc
      run: cargo test --verbose
    
  hdlc-build:
    name: Build hdlc
    runs-on: ubuntu-latest
    needs: [hdllang-build]
    steps:
    - uses: actions/checkout@v3
    - name: Build hdlc
      working-directory: ./hdlc
      run: cargo build --verbose
    
  hdlc-test:
    name: Test hdlc
    runs-on: ubuntu-latest
    needs: [hdlc-build]
    steps:
    - uses: actions/checkout@v3
    - name: Test hdlc
      working-directory: ./hdlc
      run: cargo test --verbose

# TODO add iverilog tests
# TODO add fuzzer tests
