name: Main CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-main:
    name: Cargo build & test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Test
      working-directory: ./hdlc
      run: cargo test -p hdl -p hdllang --verbose
    
# TODO add iverilog tests
# TODO add fuzzer tests
