name: Rust format
on: pull_request

jobs:
  format:
    name: "Format rust code"
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
      
    - name: Use nightly toolchain for formatting
      run: rustup default nightly

    - name: Run cargo fmt
      run: cargo fmt --all
      
    - name: Commit & push changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: '[bot] Format Rust code'